version: "3.9"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: time-table-backend
    ports:
      - 8090:8090
    restart: always
#    depends_on:
#      - database


  database:
    image: postgres:15.3
    container_name: database
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=pass
      - POSTGRES_DB=db
    ports:
      - 5432:5432
#
#
#  prometheus:
#    image: prom/prometheus
#    ports:
#      - 9090:9090
#    volumes:
#      - ./config/prometheus.yml:/etc/prometheus/prometheus.yml
#    depends_on:
#      - app
#
#  grafana:
#    image: grafana/grafana
#    ports:
#      - 3000:3000
#    environment:
#      - GF_SECURITY_ADMIN_USER=admin
#      - GF_SECURITY_ADMIN_PASSWORD=admin
#    depends_on:
#      - prometheus
