version: "3.9"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: time-table-backend
    ports:
      - 8080:8080
    restart: always
    depends_on:
      - database


  database:
    image: postgres:15.3
    container_name: database
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=pass
      - POSTGRES_DB=db
    ports:
      - 5432:5432
