# This is a basic workflow to help you get started with Actions

name: CI

on:
  pull_request:
    branches: [ "master" ]
    paths-ignore:
      - '**.md'
  workflow_dispatch:

jobs:
  prepare:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2


      - name: chmod gradlew
        run: chmod +x gradlew

    build:
      runs-on: ubuntu-latest
      steps:
        - name: build gradle project
          run: ./gradlew build

    test:
      - name: Execute Gradle build
        run: ./gradlew test

      - name: Generate Jacoco report
        run: ./gradlew jacocoTestReport



    artifacts:
      needs:
      runs-on: ubuntu-latest
      steps:
        - uses: actions/upload-artifact@v3
          with:
            name: Package
            path: build/libs
