# This is a basic workflow to help you get started with Actions

name: CI

on:
  push:
    branches: [ "master" ]
    paths-ignore:
      - '**.md'

  pull_request:
    paths-ignore:
      - '**.md'
  workflow_dispatch:

jobs:
  backend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: show
        run: ls -al
      - name: change dir
        run: cd ./backend 
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2

      - name: chmod gradlew
        run: chmod +x gradlew
          -
      - name: build gradle project
        run: ./gradlew build

      - name: Execute Gradle build
        run: ./gradlew test

      - name: Generate Jacoco report
        run: ./gradlew jacocoTestReport

      - uses: actions/upload-artifact@v3
        with:
          name: Package
          path: build/libs
