# This is a basic workflow to help you get started with Actions

name: CI

on:
  push:
    branches: [ "master" ]
    paths-ignore:
      - '**.md'

  pull_request:
    paths-ignore:
      - '**.md'
  workflow_dispatch:

jobs:
  backend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'corretto'
      

      - name: Setup Gradle
        working-directory: ./backend
        uses: gradle/gradle-build-action@v2

      - name: chmod gradlew
        working-directory: ./backend
        run: chmod +x ./gradlew
          -
      - name: build gradle project
        working-directory: ./backend
        run: ./gradlew build

      - name: Execute Gradle build
        working-directory: ./backend
        run: ./gradlew test

      - name: Generate Jacoco report
        working-directory: ./backend
        run: ./gradlew jacocoTestReport

      - uses: actions/upload-artifact@v3
        working-directory: ./backend
        with:
          name: Package
          path: build/libs
